In [1]:
import numpy as np

Numpy
Main Object
- Homogenous
    - Multidim array
    - Data should be of same type
    - Indexed by tuples
- Dimensions are called axes
eg : [[1 2 3][4 5 6]] is having axes/dimension=2


ndarray
- .ndim : no of dimensions
- .shape : shape in tuple
- .size : total no of elements
- .dtype : Type of array
- .data : memory occupied location

In [2]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.data)

2
(3, 3)
9
int32


Array Creation
- a=np.array([[1,2,3],[4,5,6],[7,8,9]])
    - function takes tuple/list as data of array
    - Can also specify datatype
    - eg: np.array(2,3,4) -> Invalid
    - a=np.array([1,2],dtype=complex)
- Predefined Function for creation
    - np.zeros((3,4)) : Puts 0's in all array values
    - np.ones  : Puts 1's in all array values
    - np.empty : Puts Random Values
    - *Takes tuple of shape as parameter*
    - By default, datatype is F64
- np.arange(init,final,step)
    - Generates values betwee init to end with step as incrementing factor
    - Takes integer values only
- np.linspace(a,b,c)
    - For Float
    - a-: Start b-:End c-: No of Elements Reqd.

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2],dtype=complex)

In [4]:
np.array(2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [5]:
print(np.zeros((3,4)))
print(np.ones((3,4)))
print(np.empty((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
np.arange(0,18,2).reshape(3,3)

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [7]:
np.linspace(0,20,16).reshape(4,4)

array([[ 0.        ,  1.33333333,  2.66666667,  4.        ],
       [ 5.33333333,  6.66666667,  8.        ,  9.33333333],
       [10.66666667, 12.        , 13.33333333, 14.66666667],
       [16.        , 17.33333333, 18.66666667, 20.        ]])

Basic Operations
- +, -, ** , *, logicals : all work elementwise.
- np.dot(A,B) : Matrix Multiplication.
- a.sum()
    - Sum of Row/Col
    - axis parameter can be specified
    - axis=0 : Col's sum
    - axis=1 : Row's sum
- np.min(), np.max()
    - Work similarly to sum() function with axis parameter.


In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.ones((3,3))
print(a+b)
print(a*b)
print(a**2)
print(a==b)
print(a.sum())
print(a.sum(axis=1))
print(a.min(axis=0))
print(a.min(axis=1))
print(a.max(axis=0))

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ True False False]
 [False False False]
 [False False False]]
45
[ 6 15 24]
[1 2 3]
[1 4 7]
[7 8 9]


Universal functions
- sin(),cos(),exp(),sqrt().. etc.
- All apply elementwise

In [9]:
print(np.sin(a),"\n")
print(np.cos(a),"\n")
print(np.exp(a),"\n")
print(np.sqrt(a),"\n")

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]] 

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]] 

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]] 

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]] 



**Indexing, Slicing, Iterating**
- a=np.arange(10)**2
    - a[2]=4 : Used to find thing at a particular index
    - a[2:5] : used to read values from starting index till ending index
    - a[:6:2] : used to read values from starting index till ending index with a jump of 2.
- From functions 
    - np.fromfunction(fn,shape in tuple,dtype of array)
- for multidim array
    - C[:,2,:2,2:3,4] // where after every , is a new dimension.
- a.flat()
    - Converts A to 1D array
- Iteration is done always wrt axes in down side.

In [10]:
a=np.arange(10)**2
print(a)
print(a[2])
print(a[2:5])
print(a[:6:2])

[ 0  1  4  9 16 25 36 49 64 81]
4
[ 4  9 16]
[ 0  4 16]


In [11]:
def fn(x,y):
    return x+y
np.fromfunction(fn,(5,4),dtype=int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [12]:
print(a)
for x in a.flat:
    print(x)

[ 0  1  4  9 16 25 36 49 64 81]
0
1
4
9
16
25
36
49
64
81


Shape Manipulation
- Many operations but all return array, do not modify the given one.
- a.ravel() : Returns Flatted array
- a.reshape((a,b)) : Return the array whose shape has been changed.
- a.T : Transposes the array
- a.resize(a,b): Changes the array's shape.

In [13]:
a=np.arange(12).reshape(3,4)
print(a)
print(a.ravel())
print(a.reshape(2,6))
print(a)
print(a.T)
a.resize(2,6)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Stacking
- np.vstack(a,b) Stacks a above b
    - Should have same no of columns
    - a/b type
- np.hstack(a,b) Stacks a side by side to b
    - Should have same no of rows.
- np.col_stack((a,b))
    - Stack columns to form a 2D array.

In [14]:
a=np.array([1,2])
b=np.array([4,3])
np.column_stack((a,b))

array([[1, 4],
       [2, 3]])

In [15]:
np.vstack((a,b))

array([[1, 2],
       [4, 3]])

In [16]:
a=a.T
b=b.T
np.hstack((a,b))

array([1, 2, 4, 3])

**Copies & Views**
- 3 Cases
- **No Copy at All**
    - No copy is made, python passes mutable objects as reference.
- **View or Shallow Copy**
    - Array can change, but addr of elements is same.
    - c=a.view() , c will share elements having same addr as a.
    - if we change value in c, a will change.
- **DeepCopy**
    - Makes a complete copy of array.

Other Functions
- np.eye(x) : Returns a x*x Identity array.
- np.linalg.inv(a) : Returns inverse of array a.